language: java

jdk:
    - openjdk7
    - oraclejdk7

script:
    - ./gradlew check

deploy:
    provider: heroku
    api_key:
        secure: a88195eb-a538-4bb0-bc55-184f5cac9ae2
    app:
        master: VidTech
    on:
        repo: LeyniRepo
