/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eythort09' at '10/27/14 5:12 PM' with Gradle 2.1
 *
 * @author eythort09, @date 10/27/14 5:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
